In [1]:
import math
import pandas as pd
import numpy as np
from sympy import *
import random

Формула 1 / (1 + x) Где x в анг   
Конвертер https://alvin-almazov.ru/calculator/odds-converter/  
Честный коэф  
https://alvin-almazov.ru/calculator/bookmaker-margin/  
На данный момент порог 1.07-1.08-1.09

In [55]:
# Вероятность букмекера что фаворит победит
x = 1/5
alpha = 1
beta = 1

In [56]:
K = 1/(1+(beta*(x))**(alpha))*100
print(f'Вероятность букмекера что фаворит выиграет: {round(K)}%')

Вероятность букмекера что фаворит выиграет: 83%


In [57]:
# 2016-21 years
x = x
alpha =  1.29
beta = 1.75

In [58]:
# test
x = x
alpha =  1.29
beta = 1.75

In [59]:
# Вероятность моя, что фаворит победит с коэф из книги
# x = x
# alpha_ =  1.16
# beta_ = 1.25

In [60]:
K_pred = 1/(1+(beta*(x))**(alpha))*100
print(f'Вероятность моя, что фаворит выиграет: {round(K_pred)}%')

Вероятность моя, что фаворит выиграет: 79%


In [185]:
# Критерий Келли
# С – размер ставки (% от банка).
# Кф – коэффициент исхода.
# В – вероятность исхода, определяемая игроком (от 0.1 до 1).
# C = (Кф * В – 1) / (Кф – 1) * 100

In [22]:
def C_c ():
    koef = float(input("Ввести средний коэффициент букмекера "))
    B = float(input("Ввести расчитанный выше процент уверенности  "))
    bank = int(input("Ввести размер банка "))
    print('Размер ставки')
    percent =  (koef * B - 1) / (koef - 1)
    return round(percent * bank, 0)

In [23]:
C_c()

Ввести средний коэффициент букмекера 1.09
Ввести расчитанный выше процент уверенности  0.79
Ввести размер банка 13500
Размер ставки


-20835.0


### Логистическая регрессия для построения модели подсчета коэф alpha beta

Подбор коэф по классической формуле логита взято из Essential Math 284 p.

y = 1 / 1. 0 + e−(β0+β1x)

In [2]:
# #points = list(pd.read_excel("Ставки_теннис.xlsx", sheet_name = 'Ставки расчет' ).itertuples())
# points = list(pd.read_excel("tennis1819.xlsx", sheet_name = '1' ).itertuples())
# b1, b0, i, n = symbols('b1 b0 i n')
# x, y = symbols('x y', cls=Function)
# joint_likelihood = Sum(log((1.0 / (1.0 + exp(-(b0 + b1 * x(i))))) ** y(i) \
# * (1.0 - (1.0 / (1.0 + exp(-(b0 + b1 * x(i)))))) ** (1 - y(i))), (i, 0,
# n))
# # Partial derivative for m, with points substituted
# d_b1 = diff(joint_likelihood, b1) \
# .subs(n, len(points) - 1).doit() \
# .replace(x, lambda i: points[i].x) \
# .replace(y, lambda i: points[i].y)
# # Partial derivative for m, with points substituted
# d_b0 = diff(joint_likelihood, b0) \
# .subs(n, len(points) - 1).doit() \
# .replace(x, lambda i: points[i].x) \
# .replace(y, lambda i: points[i].y)
# # compile using lambdify for faster computation
# d_b1 = lambdify([b1, b0], d_b1)
# d_b0 = lambdify([b1, b0], d_b0)
# # Perform Gradient Descent
# b1 = 0.1
# b0 = 0.1
# L = .01
# for j in range(1000):
#     b1 += d_b1(b1, b0) * L
#     b0 += d_b0(b1, b0) * L
# print(b1, b0)

Алгоритм отработал

In [154]:
# #points = list(pd.read_csv("Ставки расчет.csv").itertuples())
# points = list(pd.read_excel("tennis1819.xlsx", sheet_name = '1' ).itertuples())
# b1, b0, i, n = symbols('b1 b0 i n')
# x, y = symbols('x y', cls=Function)
# joint_likelihood = Sum(log((1.0 / (1.0 + (x(i))*b0**(b1))) ** y(i) \
# * (1.0 - (1.0 / (1.0 + (x(i))*b0**(b1)))) ** (1 - y(i))), (i, 0,
# n))
# # Partial derivative for m, with points substituted
# d_b1 = diff(joint_likelihood, b1) \
# .subs(n, len(points) - 1).doit() \
# .replace(x, lambda i: points[i].x) \
# .replace(y, lambda i: points[i].y)
# # Partial derivative for m, with points substituted
# d_b0 = diff(joint_likelihood, b0) \
# .subs(n, len(points) - 1).doit() \
# .replace(x, lambda i: points[i].x) \
# .replace(y, lambda i: points[i].y)
# # compile using lambdify for faster computation
# d_b1 = lambdify([b1, b0], d_b1)
# d_b0 = lambdify([b1, b0], d_b0)
# # Perform Gradient Descent
# b1 = 1
# b0 = 1
# L = .01
# for j in range(10_000):
#     b1 += d_b1(b1, b0) * L
#     b0 += d_b0(b1, b0) * L
# print(b1, b0)

In [7]:
   ######  Обозначения #####
#  b0 = beta 
#  b1 = alpha
# x = x

In [155]:
def logistic_K(alpha, beta, x):
    p = 1/(1+(beta*x)**(alpha))*100
    return p

Проверять по коду выше чтобы не было сильной разницы

### След этап сбор данных прошлых матчей для подсчета коэф

Источник: https://www.tennisexplorer.com/picks/archive/?month=May-2021


Собрал янв21-янв22 в Ставки.csv  

Сбор данных 2018-19-20-21 год  
Сбор данных 2017-16 без учета маржы (как гипотеза)  
Переделать все данные без маржи

In [2]:
data = pd.read_excel('tennis1819.xlsx')
data.shape

(2648, 3)

In [2]:
# points = list(pd.read_excel("Ставки_теннис.xlsx", sheet_name = 'Ставки расчет' ).itertuples())
points = list(pd.read_excel("tennis1819.xlsx", sheet_name = '2').itertuples())
b1, b0, i, n = symbols('b1 b0 i n')
x, y = symbols('x y', cls=Function)
joint_likelihood = Sum(log((1.0 / (1.0 + (x(i))*(b0**(b1)))) ** y(i) \
* (1.0 - (1.0 / (1.0 + (x(i))*(b0**(b1))))) ** (1 - y(i))), (i, 0,
n))
# Partial derivative for m, with points substituted
d_b1 = diff(joint_likelihood, b1) \
.subs(n, len(points) - 1).doit() \
.replace(x, lambda i: points[i].x) \
.replace(y, lambda i: points[i].y)
# Partial derivative for m, with points substituted
d_b0 = diff(joint_likelihood, b0) \
.subs(n, len(points) - 1).doit() \
.replace(x, lambda i: points[i].x) \
.replace(y, lambda i: points[i].y)
# compile using lambdify for faster computation
d_b1 = lambdify([b1, b0], d_b1)
d_b0 = lambdify([b1, b0], d_b0)
# Perform Gradient Descent
b1 = 0
b0 = 1
L = 0.0001
for j in range(10_000):
    b1 += d_b1(b1, b0) * L
    b0 += d_b0(b1, b0) * L
print(b1, b0)

0.0 1.0


In [52]:
# 6 years till bis 2021-2016
# points = list(pd.read_excel("Ставки_теннис.xlsx", sheet_name = 'Ставки расчет' ).itertuples())
points = list(pd.read_csv("tennish2o.csv").itertuples())
b1, b0, i, n = symbols('b1 b0 i n')
x, y = symbols('x y', cls=Function)
joint_likelihood = Sum(log((1.0 / (1.0 + (x(i))*(b0**(b1)))) ** y(i) \
* (1.0 - (1.0 / (1.0 + (x(i))*(b0**(b1))))) ** (1 - y(i))), (i, 0,
n))
# Partial derivative for m, with points substituted
d_b1 = diff(joint_likelihood, b1) \
.subs(n, len(points) - 1).doit() \
.replace(x, lambda i: points[i].x) \
.replace(y, lambda i: points[i].y)
# Partial derivative for m, with points substituted
d_b0 = diff(joint_likelihood, b0) \
.subs(n, len(points) - 1).doit() \
.replace(x, lambda i: points[i].x) \
.replace(y, lambda i: points[i].y)
# compile using lambdify for faster computation
d_b1 = lambdify([b1, b0], d_b1)
d_b0 = lambdify([b1, b0], d_b0)
# Perform Gradient Descent
b1 = 1
b0 = 1
L = 0.0001
for j in range(10000):
    b1 += d_b1(b1, b0) * L
    b0 += d_b0(b1, b0) * L
print(b1, b0)

1.2923554102295143 1.7592281127420586


Предсказание на февраль - часть апреля
1. Предсказание букмекера
2. Мое предсказание
3. Использование критерия Келли для шансов банка
4. Итог: минус 1700

Эти коэф ужасны. Не превышают 20% т.е. не ставить никогда
Два три пути:
1. Использовать exp функцию 
2. Использовать готовые коэф по умолчанию
3. Использовать другой датасет (есть вероятность неверной интерпретации ставок)

Для банка использовать коэф букмекера и свой процент высчитанный по лог-рег

Коэф были черезчур оптимистичны. Выбрал начальные меньше (0.1). Если еще меньше то плохо (отриц)  
Добавлять данные дальше - взять 2020 год. Готово  
Сделал краулер - теперь можно собирать быстрее, 2019-2018 собрал обрабатываю



В качестве эксперимента привожу модель из sklearn

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, accuracy_score, confusion_matrix 
import seaborn as sns
import matplotlib.pyplot as plt

In [67]:
#data = pd.read_excel("Ставки_теннис.xlsx", sheet_name = 'Ставки расчет')
data = pd.read_csv("tennish2o.csv")

In [68]:
data.head()

x  y
0  0.74  1
1  0.31  0
2  0.85  1
3  0.20  0
4  0.74  1

In [69]:
X = data.drop(columns=['y'], axis=1) 
Y = data.y.values

np.random.seed(22)
X_train, X_test, y_train, y_test = train_test_split(X, Y)

In [70]:
Y

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [71]:
model1 = LogisticRegression(max_iter=10000, penalty='l2', C=0.001)
model1.fit(X_train, y_train)

LogisticRegression(C=0.001, max_iter=10000)

In [72]:
y_train_hat = model1.predict(X_train)
y_train_hat_probs = model1.predict_proba(X_train)[:,1]

train_accuracy = accuracy_score(y_train, y_train_hat)*100
train_auc_roc = roc_auc_score(y_train, y_train_hat_probs)*100

print('Confusion matrix:\n', confusion_matrix(y_train, y_train_hat))

print('Training AUC: %.4f %%' % train_auc_roc)

print('Training accuracy: %.4f %%' % train_accuracy)

Confusion matrix:
 [[1478  815]
 [ 698 1606]]
Training AUC: 72.6963 %
Training accuracy: 67.0872 %


In [73]:
y_test_hat = model1.predict(X_test)
y_test_hat_probs = model1.predict_proba(X_test)[:,1]

test_accuracy = accuracy_score(y_test, y_test_hat)*100
test_auc_roc = roc_auc_score(y_test, y_test_hat_probs)*100

print('Confusion matrix:\n', confusion_matrix(y_test, y_test_hat))

print('Testing AUC: %.4f %%' % test_auc_roc)

print('Testing accuracy: %.4f %%' % test_accuracy) 

Confusion matrix:
 [[476 296]
 [215 546]]
Testing AUC: 72.8165 %
Testing accuracy: 66.6667 %


In [83]:
model1.predict_proba([[0.79]]) # честная уверенность букм.

array([[0.48679831, 0.51320169]])

In [22]:
#Т.е. эта модель предсказывет 0 с вероятностью {}% и 1 с вероятностью {}

In [23]:
print(model1.coef_.flatten())

[-0.56238194]


In [15]:
print(model1.intercept_.flatten())

[1.27770581]


In [16]:
model1.coef_

array([[-0.56238194]])

In [59]:
C_c()

Ввести средний коэффициент букмекера 1.6
Ввести расчитанный выше процент уверенности  0.53
Ввести размер банка 1000
Размер ставки


-253.0

### Футбол

##### Уравнение лог регрессии

1.0/1.0 + x*b0**b1

In [85]:
# На кого ставить
# если разница > 0.4 на фаворита (хозяев)
# если разница < 0.15 то ничья

In [2]:
def what_bet():
    h = float(input("Введите честный коэф хозяев(фаворита) "))
    g = float(input("Введите честный коэф гостей(аутсайдера) "))
    h_ = round((100/h/100),2)
    g_ = round((100/g/100),2)
    delta = round((h_ - g_), 2)
    print("Разница", delta)
    if delta > 0.4:
        print("Ставить на хозяев")
    elif delta < 0.15:
        print("Ставить на ничью")
    else: print("Не ставить")

In [5]:
what_bet()

Введите честный коэф хозяев(фаворита) 1.26
Введите честный коэф гостей(аутсайдера) 17.09
Разница 0.73
Ставить на хозяев


In [4]:
def C_c ():
    koef = float(input("Ввести обычный коэффициент букмекера "))
    B = float(input("Ввести расчитанный выше процент уверенности  "))
    bank = int(input("Ввести размер банка "))
    print('Размер ставки')
    percent =  (koef * B - 1) / (koef - 1)
    return round(percent * bank, 0)

In [5]:
#   Если ничья мой прогноз 34,7% если фаворит, то 75%
def percent_book():
    p = float(input("Ввести честный коэффициент букмекера "))
    p_ = round((100/p/100),2)
    print('Процент уверенности букмекера ', p_, 'а мой процент 0.35 на ничью и 0.75 на фаворита')

In [6]:
percent_book()

Ввести честный коэффициент букмекера 1.66
Процент уверенности букмекера  0.6 а мой процент 0.35 на ничью и 0.75 на фаворита


In [ ]:
# мой процент уверенности для критерия Келли
# вероятность ничьей устанавливается равной 0,355 – 0,25* (p – q)


In [8]:
# P = 1 / (1+(p/1-p) **(-1.06))

def P_fav():
    p = float(input('Enter p bookmaker '))
    p_ = p / (1-p)
    power = pow(p_, (-1.06))
    znam = 1 + 0.961*power
    prob = round((1/znam),2)
    print('Мой процент уверенности в победе фаворита: ',prob)

In [9]:
P_fav()

Enter p bookmaker 0.6
Мой процент уверенности в победе фаворита:  0.62


In [76]:
def P_x():
    p = float(input('Enter p bookmaker P1 '))
    q = float(input('Enter p bookmaker P2 '))
    p_ = p - q
    prob = 0.355 - 0.25 * p_
    print('Мой процент уверенности в ничьей: ', prob)

In [77]:
P_x()

Enter p bookmaker P1 2.93
Enter p bookmaker P2 2.88
Мой процент уверенности в ничьей:  0.3424999999999999


In [11]:
C_c ()

Ввести обычный коэффициент букмекера 1.61
Ввести расчитанный выше процент уверенности  0.62
Ввести размер банка 5000
Размер ставки


-15.0

In [112]:
# работа с формулой логистической регрессии с нуля - все у меня правильно

In [93]:
data = pd.read_excel('tennis1819.xlsx')

In [95]:
patient_data = data.drop(columns=['Unnamed: 0'], axis=1)

In [96]:
patient_data =  patient_data.itertuples()

In [97]:
b0 = 1
b1 = 1

In [105]:
def K(x):
    p = 1/(1+(b0*x)**(b1))
    return p

In [106]:
K(1/10)

0.9090909090909091

In [107]:
joint_likelihood = 1.0

In [108]:
for p in patient_data:
    if p.y == 1.0:
        joint_likelihood *= K(p.x)
    elif p.y == 0.0:
        joint_likelihood *= (1.0 - K(p.x))

In [109]:
print(joint_likelihood)

1.0


#### Развернем кластер h2o и применим логистическую регрессию к моим данным

In [20]:
import h2o

In [21]:
h2o.init(nthreads=-1, max_mem_size=8)

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
  Starting server from C:\Users\e.kirichenko\Anaconda3\Lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\E7D3E~1.KIR\AppData\Local\Temp\tmpd11q7mfz
  JVM stdout: C:\Users\E7D3E~1.KIR\AppData\Local\Temp\tmpd11q7mfz\h2o_e_kirichenko_started_from_python.out
  JVM stderr: C:\Users\E7D3E~1.KIR\AppData\Local\Temp\tmpd11q7mfz\h2o_e_kirichenko_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.


--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Europe/Moscow
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.34.0.7
H2O_cluster_version_age:    5 months and 25 days !!!
H2O_cluster_name:           H2O_from_python_e_kirichenko_pm09g3
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    7.103 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.9.7 final
--------------------------  ---------------------------------------------------------

In [38]:

h2o_data = h2o.upload_file('tennish2o.csv')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%


In [39]:
h2o_data.describe()

Rows:6130
Cols:2




x y 
 
 
 type real int 
 mins 0.04 0.0 
 mean 0.5289853181076659 0.5 
 maxs 0.99 1.0 
 sigma 0.21249026109136587 0.5000407880247039 
 zeros 0 3065 
 missing 0 0 
 0 0.74 1.0 
 1 0.31 0.0 
 2 0.85 1.0 
 3 0.2 0.0 
 4 0.74 1.0 
 5 0.32 0.0 
 6 0.5 1.0 
 7 0.57 0.0 
 8 0.38 1.0 
 9 0.68 0.0

In [40]:
dependent = 'y'

In [41]:
predictors = list(h2o_data.columns)

In [42]:
predictors

['x', 'y']

In [43]:
predictors.remove(dependent)

In [44]:
from h2o.estimators.glm import H2OGeneralizedLinearEstimator

In [45]:
model = H2OGeneralizedLinearEstimator(family='binomial')

In [46]:
model.train(predictors, dependent, training_frame=h2o_data)

glm Model Build progress: |

C:\Users\e.kirichenko\Anaconda3\lib\site-packages\h2o\estimators\estimator_base.py:206: RuntimeWarning: Response is numeric, so the regression model will be trained. However, the cardinality is equaled to two, so if you want to train a classification model, convert the response column to categorical before training.
  warnings.warn(mesg["message"], RuntimeWarning)


██████████████████████████████████████████████████████| (done) 100%
Model Details
H2OGeneralizedLinearEstimator :  Generalized Linear Modeling
Model Key:  GLM_model_python_1655297017438_1


GLM Model: summary


family   link                                regularization  \
0    binomial  logit  Elastic Net (alpha = 0.5, lambda = 3.95E-4 )   

   number_of_predictors_total number_of_active_predictors  \
0                           1                           1   

   number_of_iterations  \
0                     3   

                                           training_frame  
0  Key_Frame__upload_a470369a6eda41ed5c6c7fd762ac4b22.hex



ModelMetricsBinomialGLM: glm
** Reported on train data. **

MSE: 0.2111775210275778
RMSE: 0.4595405542795737
LogLoss: 0.6105404764638875
Null degrees of freedom: 6129
Residual degrees of freedom: 6128
Null deviance: 8497.984433665782
Residual deviance: 7485.226241447261
AIC: 7489.226241447261
AUC: 0.7270312346148831
AUCPR: 0.7169451463443396
Gini: 0.4540624692297661

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3398673334382683: 


0       1   Error              Rate
0      0  1216.0  1849.0  0.6033   (1849.0/3065.0)
1      1   401.0  2664.0  0.1308    (401.0/3065.0)
2  Total  1617.0  4513.0   0.367   (2250.0/6130.0)


Maximum Metrics: Maximum metrics at their respective thresholds


metric  threshold        value   idx
0                        max f1   0.339867     0.703088  62.0
1                        max f2   0.208938     0.837266  78.0
2                  max f0point5   0.563128     0.673454  40.0
3                  max accuracy   0.500892     0.671289  46.0
4                 max precision   0.872417     1.000000   0.0
5                    max recall   0.138008     1.000000  90.0
6               max specificity   0.872417     1.000000   0.0
7              max absolute_mcc   0.500892     0.342611  46.0
8    max min_per_class_accuracy   0.500892     0.664274  46.0
9   max mean_per_class_accuracy   0.500892     0.671289  46.0
10                      max tns   0.872417  3065.000000   0.0
11                      max fns   0.872417  3061.000000   0.0
12                      max fps   0.115015  3065.000000  95.0
13                      max tps   0.138008  3065.000000  90.0
14                      max tnr   0.872417     1.000000   0.0
15                      max fnr   0.872417     0.998695   0.0
16                      max fpr   0.115015     1.000000  95.0
17                      max tpr   0.138008     1.000000  90.0


Gains/Lift Table: Avg response rate: 50,00 %, avg score: 50,00 %


group  cumulative_data_fraction  lower_threshold      lift  \
0       1                  0.010440         0.847344  1.843750   
1       2                  0.023328         0.830444  1.822785   
2       3                  0.031974         0.818370  1.547170   
3       4                  0.041599         0.812087  1.627119   
4       5                  0.055628         0.799022  1.720930   
5       6                  0.112561         0.763437  1.530086   
6       7                  0.150408         0.740096  1.448276   
7       8                  0.211419         0.706740  1.385027   
8       9                  0.301794         0.642813  1.328520   
9      10                  0.414029         0.573362  1.232558   
10     11                  0.507015         0.500892  1.049123   
11     12                  0.600816         0.428385  0.911304   
12     13                  0.708809         0.358828  0.779456   
13     14                  0.807178         0.294742  0.660033   
14     15                  0.910114         0.230375  0.541997   
15     16                  1.000000         0.115015  0.348457   

    cumulative_lift  response_rate     score  cumulative_response_rate  \
0          1.843750       0.921875  0.856671                  0.921875   
1          1.832168       0.911392  0.837184                  0.916084   
2          1.755102       0.773585  0.821718                  0.877551   
3          1.725490       0.813559  0.812087                  0.862745   
4          1.724340       0.860465  0.801945                  0.862170   
5          1.626087       0.765043  0.776726                  0.813043   
6          1.581345       0.724138  0.746262                  0.790672   
7          1.524691       0.692513  0.717315                  0.762346   
8          1.465946       0.664260  0.667914                  0.732973   
9          1.402679       0.616279  0.604770                  0.701340   
10         1.337838       0.524561  0.532228                  0.668919   
11         1.271246       0.455652  0.457898                  0.635623   
12         1.196318       0.389728  0.388269                  0.598159   
13         1.130962       0.330017  0.321812                  0.565481   
14         1.064348       0.270998  0.259364                  0.532174   
15         1.000000       0.174229  0.188031                  0.500000   

    cumulative_score  capture_rate  cumulative_capture_rate       gain  \
0           0.856671      0.019250                 0.019250  84.375000   
1           0.845906      0.023491                 0.042741  82.278481   
2           0.839365      0.013377                 0.056117  54.716981   
3           0.833054      0.015661                 0.071778  62.711864   
4           0.825208      0.024144                 0.095922  72.093023   
5           0.800686      0.087113                 0.183034  53.008596   
6           0.786992      0.054812                 0.237847  44.827586   
7           0.766884      0.084502                 0.322349  38.502674   
8           0.737247      0.120065                 0.442414  32.851986   
9           0.701335      0.138336                 0.580750  23.255814   
10          0.670321      0.097553                 0.678303   4.912281   
11          0.637157      0.085481                 0.763785  -8.869565   
12          0.599237      0.084176                 0.847961 -22.054381   
13          0.565428      0.064927                 0.912887 -33.996683   
14          0.530811      0.055791                 0.968679 -45.800317   
15          0.500000      0.031321                 1.000000 -65.154265   

    cumulative_gain  kolmogorov_smirnov  
0         84.375000            0.017618  
1         83.216783            0.038825  
2         75.510204            0.048287  
3         72.549020            0.060359  
4         72.434018            0.080587  
5         62.608696            0.140946  
6         58.134490            0.174878  
7         52.469136        



Scoring History: 


timestamp    duration  iterations  negative_log_likelihood  \
0    2022-06-15 16:13:20   0.000 sec           0              4248.992217   
1    2022-06-15 16:13:21   0.056 sec           1              3748.115571   
2    2022-06-15 16:13:21   0.063 sec           2              3742.625506   
3    2022-06-15 16:13:21   0.070 sec           3              3742.613121   

   objective training_rmse training_logloss training_r2 training_auc  \
0   0.693147                                                           
1   0.611655                                                           
2   0.610794                                                           
3   0.610793      0.459541          0.61054     0.15529     0.727031   

  training_pr_auc training_lift training_classification_error  
0                                                              
1                                                              
2                                                              
3        0.716945       1.84375                      0.367047


Variable Importances: 


variable  relative_importance  scaled_importance  percentage
0        x             0.886423                1.0         1.0

In [49]:
model.auc(valid=True)

In [64]:
#model.predict()